const IMAGE_KIT_URL = process.env.REACT_APP_IMAGE_KIT_URL;
const IMAGE_KIT_PUBLIC_KEY = process.env.REACT_APP_IMAGE_KIT_PUBLIC_KEY;

const PRIVATE_KEY = process.env.PRIVATE_KEY;
const IMAGE_KIT_ID = process.env.REACT_APP_IMAGE_KIT_ID


export { IMAGE_KIT_URL, PRIVATE_KEY,  IMAGE_KIT_ID, IMAGE_KIT_PUBLIC_KEY };
